# Change these first
owner: TheRedNet # Your GitHub organization or username, where this repository lives
repo: stiftsupptime # The name of this repository

sites:
  - name: Homepage
    url: https://stiftsgymnasium.de
  - name: Intranet
    url: https://intranet.stifts.net
  - name: WebMail
    url: https://mail.stifts.net
  - name: Support Sytem
    url: https://support.stifts.net
  - name: Schule@BW Moodle
    url: https://04104462160.moodle.bw.schule
  - name: WebUntis
    url: https://cissa.webuntis.com/WebUntis/#/basic/login
    headers:
      - 'Cookie: schoolname="_c3RpZnRzZ3ltbmFzaXVtIHNpbmRlbGZpbmdlbg=="; Tenant-Id="4068000";'
  - name: MailXchange 1 (mx01.stifts.net)
    url: mx01.stifts.net
    port: 25
    check: "tcp-ping"
    ipv6: false
  - name: MailXchange 2 (mx02.stifts.net)
    url: mx02.stifts.net
    port: 25
    check: "tcp-ping"
    ipv6: false
  - name: MailXchange 3 (relay.rzone.de)
    url: relay.rzone.de
    port: 25
    check: "tcp-ping"
    ipv6: false

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /stiftsupptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Stiftsgymansium Status
  introTitle: "Stiftsgymnasium Server Status"
  introMessage: Probleme auf [support.stifts.net](https://support.stifts.net) oder per Mail an [support@stifts.net](mailto:support@stifts.net) melden.
  navbar:
    - title: Status
      href: /
    - title: Homepage
      href: https://stiftsgymnasium.de
    - title: Support
      href: https://support.stifts.net

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
